# Generated by Django 2.0.1 on 2018-01-16 04:16

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('slug', models.SlugField(unique=True, verbose_name='identificador')),
                ('description', models.TextField(verbose_name='descrição')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='administrador')),
            ],
            options={
                'verbose_name_plural': 'linhas',
                'verbose_name': 'linha',
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='longitude')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='latitude')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='nome')),
                ('description', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='cidade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='administrador')),
            ],
            options={
                'verbose_name_plural': 'marcadores',
                'ordering': ['city'],
                'verbose_name': 'marcador',
            },
        ),
        migrations.CreateModel(
            name='PointLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='longitude')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='latitude')),
                ('order', models.PositiveSmallIntegerField(verbose_name='ordem')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Line', verbose_name='linha')),
            ],
            options={
                'verbose_name_plural': 'pontos',
                'ordering': ['line', 'order'],
                'verbose_name': 'ponto',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('slug', models.SlugField(unique=True, verbose_name='identificador')),
                ('back', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_back', to='route.Line', verbose_name='volta')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.City', verbose_name='cidade')),
                ('front', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_front', to='route.Line', verbose_name='ida')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='administrador')),
            ],
            options={
                'verbose_name_plural': 'rotas',
                'ordering': ['name'],
                'verbose_name': 'rota',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('sunday', 'domingo'), ('monday', 'segunda'), ('tuesday', 'terça'), ('wednesday', 'quarta'), ('thursday', 'quinta'), ('friday', 'sexta'), ('saturday', 'sábado')], max_length=9), size=None, verbose_name='dias da semana')),
                ('hour', models.TimeField(verbose_name='hora')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Line', verbose_name='linha')),
            ],
            options={
                'verbose_name_plural': 'horários',
                'ordering': ['line', 'hour'],
                'verbose_name': 'horário',
            },
        ),
    ]
