# Generated by Django 2.0.1 on 2018-01-17 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_marker_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marker',
            name='name',
        ),
    ]
