# Generated by Django 2.0.1 on 2018-01-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_auto_20180120_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='título'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marker',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='identificador'),
            preserve_default=False,
        ),
    ]
